title: SNHU Capstone
baseurl: "/snhu-capstone"
url: "https://danruppert-snhu.github.io"

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

markdown: kramdown
